version: '3'

networks:
  web:
    external: true

volumes:
  data:

services:
  postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/dolibarr/sql:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.fpm
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - data:/var/www/html
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/dolibarr/conf:/var/www/html/conf
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/dolibarr/documents:/var/www/html/documents

  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - app
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: dolibarr.${CHATONS_DOMAIN:-localhost}, www.dolibarr.${CHATONS_DOMAIN:-localhost}"
    networks:
      - web
      - default
    volumes:
      - data:/var/www/html:ro
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/dolibarr/conf:/var/www/html/conf:ro
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/dolibarr/documents:/var/www/html/documents:ro
