version: '2'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - /srv/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    env_file:
      - .env

  app:
    image: nextcloud
    links:
      - db
    volumes:
      - /srv/nextcloud/app:/var/www/html
    restart: always
    ports:
      - "127.0.0.1:9000:80"
