version: '3'

networks:
  traefik:
    external: true

services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    env_file:
      - .env
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/nextcloud/db:/var/lib/mysql

  app:
    image: nextcloud
    restart: always
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db:3306
    env_file:
      - .env
    labels:
      traefik.enable: "true"
      traefik.backend: "nextcloud"
      traefik.frontend.rule: "Host: cloud.${CHATONS_DOMAIN:-local}, www.cloud.${CHATONS_DOMAIN:-local}"
      traefik.docker.network: "traefik"
    networks:
      - traefik
      - default
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/nextcloud/app:/var/www/html

  pma:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    environment:
      - MYSQL_USER=nextcloud
      - PMA_HOSTS=db
      - PMA_PORT=3306
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: pma.${DOMAIN_NAME:-local}"
      traefik.docker.network: "traefik"
      traefik.backend: "cloudpma"
    networks:
      - traefik
      - default
