version: '3'

services:
  app:
    image: containous/whoami
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - web
    labels:
      traefik.enable: "true"
      traefik.http.routers.whoami.rule: "Host(`whoami.${CHATONS_DOMAIN:-localhost}`)"

networks:
  web:
    external: true
