version: '2'

services:
  app:
    image: registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /etc/letsencrypt/live/oxyta.net:/certs
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/fullchain.pem
      - REGISTRY_HTTP_TLS_KEY=/certs/privkey.pem
