version: '2'

services:
  app:
    image: gitlab/gitlab-ce
    restart: always
    hostname: 'git.oxyta.net'
    environment:
      - GITLAB_OMNIBUS_CONFIG |
        external_url 'https://git.oxyta.net'
        gitlab_rails['gitlab_ssh_host'] = 'oxyta.net'
    volumes:
      - /srv/gitlab/app/config:/etc/gitlab
      - /srv/gitlab/app/logs:/var/log/gitlab
      - /srv/gitlab/app/data:/var/opt/gitlab
    restart: always
    ports:
      - "127.0.0.1:9002:80"
      - "22:22"
