version: '3'

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
  postgres:
    image: postgres:11-alpine
    restart: unless-stopped
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/nextcloud/db:/var/lib/postgresql/data
  sentry:
    image: sentry
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - web
      - default
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: sentry.${CHATONS_DOMAIN:-localhost}, www.sentry.${CHATONS_DOMAIN:-localhost}"
    environment:
      - SENTRY_REDIS_HOST=redis
      - SENTRY_POSTGRES_HOST=postgres
      - SENTRY_SERVER_EMAIL=sentry@${CHATONS_DOMAIN:-localhost}
  cron:
    command: "sentry run cron"
    image: sentry
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SENTRY_REDIS_HOST=redis
      - SENTRY_POSTGRES_HOST=postgres
  worker:
    command: "sentry run worker"
    image: sentry
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SENTRY_REDIS_HOST=redis
      - SENTRY_POSTGRES_HOST=postgres

networks:
  web:
    external: true
