version: '2'

volumes:
  sql:

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
  postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    volumes:
      - "sql:/var/lib/postgresql/data"
  sentry:
    image: sentry
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - web
      - default
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: sentry.${DOMAIN_NAME}, www.sentry.${DOMAIN_NAME}"
    environment:
      - SENTRY_REDIS_HOST=redis
      - SENTRY_POSTGRES_HOST=postgres
      - SENTRY_SERVER_EMAIL=sentry@${DOMAIN_NAME}
  cron:
    command: "sentry run cron"
    image: sentry
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SENTRY_REDIS_HOST=redis
      - SENTRY_POSTGRES_HOST=postgres
  worker:
    command: "sentry run worker"
    image: sentry
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SENTRY_REDIS_HOST=redis
      - SENTRY_POSTGRES_HOST=postgres

networks:
  web:
    external: true
