version: '3'

networks:
  proxytanet:
    external: true

services:
  db:
    image: postgres:10-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/etherpad/db:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    env_file:
      - .env
    labels:
      traefik.enable: "true"
      traefik.backend: "etherpad"
      traefik.frontend.rule: "Host: pad.${CHATONS_DOMAIN:-local}, www.pad.${CHATONS_DOMAIN:-local}"
      traefik.docker.network: "proxytanet"
    networks:
      - default
      - proxytanet
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/etherpad/app:/opt/etherpad-lite/var
