version: '3'

networks:
  web:
    external: true

services:
  db:
    image: postgres:10-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/${CHATONS_SERVICE:-pad}/db:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: ${CHATONS_SERVICE:-pad}.${CHATONS_DOMAIN:-localhost}, www.${CHATONS_SERVICE:-pad}.${CHATONS_DOMAIN:-localhost}"
    networks:
      - default
      - web
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/${CHATONS_SERVICE:-pad}/app:/opt/etherpad-lite/var
