version: '2'

services:
  db:
    image: mysql
    restart: always
    volumes:
      - /srv/etherpad/db:/var/lib/mysql
    env_file:
      - .env

  app:
    image: tvelocity/etherpad-lite
    restart: always
    links:
      - db
    env_file:
      - .env
    environment:
      - ETHERPAD_DB_HOST=db
    ports:
      - "127.0.0.1:9001:9001"
