version: '2'

services:
  db:
    image: mysql
    restart: always
    volumes:
      - /srv/etherpad/db:/var/lib/mysql
    env_file:
      - .env

  app:
    build: .
    restart: always
    links:
      - db
    volumes:
      - /srv/etherpad/app:/opt/etherpad-lite/var
    env_file:
      - .env
    environment:
      - ETHERPAD_DB_HOST=db
      - ETHERPAD_TITLE=Bloc Note
    ports:
      - "127.0.0.1:9001:9001"
