version: '2'

services:
  generate:
    image: silviof/docker-matrix
    restart: always
    environment:
      - SERVER_NAME=im.oxyta.net
      - REPORT_STATS=no
    volumes:
      - /srv/matrix/app/:/data
    command: generate
  app:
    image: silviof/docker-matrix
    restart: always
    ports:
      - "8448:8448"
      - "3478:3478"
    volumes:
      - /srv/matrix/app/:/data
    command: start
