version: '3'

networks:
  web:
    external: true

services:
  app:
    image: shaarli/shaarli:latest
    restart: unless-stopped
    volumes:
      - cache:/var/www/shaarli/cache
      - data:/var/www/shaarli/data
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: links.${CHATONS_DOMAIN:-localhost}, www.links.${CHATONS_DOMAIN:-localhost}"
    networks:
      - web
      - default

volumes:
  cache:
  data:
