version: '3'

services:
  traefik:
    image: traefik
    command: --acme.email=${CHATONS_MAIL}
    restart: always
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:8080:8080
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CHATONS_ROOT_DIR}/traefik/acme.json:/acme.json
      - ${CHATONS_ROOT_DIR}/traefik/traefik.toml:/traefik.toml

### NETWORKS

networks:
  traefik:
    external: true
