debug = false
checkNewVersion = true
logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[web]
# web ui on 8080

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.redirect]
    # For this to work, there must be a corresponding frontend rule
    # See https://github.com/containous/traefik/issues/919#issuecomment-311033114
    regex = "^https://www.(.*)"
    replacement = "https://$1"
  [entryPoints.https.tls]

[docker]
# the domain is set on the command line
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = true
domain = "docker.localhost"

[acme]
# the email is set on the command line
storage = "acme.json"
entryPoint = "https"
OnHostRule = true
#acmeLogging = true
#caServer = "https://acme-staging.api.letsencrypt.org/directory"
[acme.httpChallenge]
  entryPoint = "http"

