version: '3'

networks:
  web:
    external: true

services:
  app:
    image: shaarli/shaarli:latest
    restart: unless-stopped
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/${CHATONS_DOMAIN:-links}/data:/var/www/shaarli/data
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: ${CHATONS_DOMAIN:-links}.${CHATONS_DOMAIN:-localhost}, www.${CHATONS_DOMAIN:-links}.${CHATONS_DOMAIN:-localhost}"
    networks:
      - web
