version: '3'

networks:
  web:
    external: true

services:
  shaarli:
    build: ./shaarli
    restart: unless-stopped
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/${CHATONS_SERVICE:-links}/data:/var/www/shaarli/data
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: ${CHATONS_SERVICE:-links}.${CHATONS_DOMAIN:-localhost}, www.${CHATONS_SERVICE:-links}.${CHATONS_DOMAIN:-localhost}"
    networks:
      - web
