version: "3"

networks:
  web:
    external: true

services:
  matrix:
    image: matrixdotorg/synapse:v1.12.3-py3
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SYNAPSE_NO_TLS=true
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: ${CHATONS_SERVICE:-matrix}.${CHATONS_DOMAIN:-localhost}, www.${CHATONS_SERVICE:-matrix}.${CHATONS_DOMAIN:-localhost}"
    networks:
      - web
      - default
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/${CHATONS_SERVICE:-matrix}/data:/data

  db:
    image: postgres:10-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/${CHATONS_SERVICE:-matrix}/postgres:/var/lib/postgresql/data

  riot:
    build:
      context: .
      args:
        SYNAPSE_FULL_URL: ${CHATONS_SERVICE:-matrix}.${CHATONS_DOMAIN:-localhost}
        CHATONS_DOMAIN: ${CHATONS_DOMAIN:-localhost}
        RIOT_VERSION: v1.5.15
        PROTOCOL: ${PROTOCOL:-http}
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: ${RIOT_SUBDOMAIN:-riot}.${CHATONS_DOMAIN:-localhost}, www.${RIOT_SUBDOMAIN:-riot}.${CHATONS_DOMAIN:-localhost}"
    networks:
      - web
