version: "3"

networks:
  web:
    external: true

services:
  synapse:
    image: matrixdotorg/synapse:v1.37.1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SYNAPSE_NO_TLS=true
    labels:
      traefik.enable: "true"
      traefik.http.routers.matrix-app.rule: "Host(`${CHATONS_SERVICE:-matrix}.${CHATONS_DOMAIN:-localhost}`)"
    networks:
      - web
      - default
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/${CHATONS_SERVICE:-matrix}/data:/data

  db:
    image: postgres:10-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/${CHATONS_SERVICE:-matrix}/postgres:/var/lib/postgresql/data

  element:
    image: vectorim/element-web:v1.7.31
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.matrix-element.rule: "Host(`${ELEMENT_SUBDOMAIN:-element}.${CHATONS_DOMAIN:-localhost}`)"
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/${CHATONS_SERVICE:-matrix}/config.json:/app/config.json
    networks:
      - web
