version: '3'

networks:
  proxytanet:
    external: true

services:
  app:
    build: .
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.backend: "homepage"
      traefik.frontend.rule: "Host: ${CHATONS_DOMAIN:-local}, www.${CHATONS_DOMAIN:-local}"
    networks:
      - proxytanet
