version: '3'

networks:
  web:
    external: true

services:
  homepage:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: ${CHATONS_DOMAIN:-localhost}, www.${CHATONS_DOMAIN:-localhost}"
    networks:
      - web
