version: '3'

networks:
  web:
    external: true

services:
  kuma:
    image: louislam/uptime-kuma:1-alpine
    restart: unless-stopped
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/${CHATONS_SERVICE:-status}/data:/app/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.status.rule: "Host(`${CHATONS_SERVICE:-status}.${CHATONS_DOMAIN:-localhost}`)"
      traefik.http.services.status.loadBalancer.server.port: "3001"
      traefik.http.middlewares.links.headers.frameDeny: 'true'
    networks:
      - web
