version: '3'

networks:
  web:
    external: true

volumes:
  data:

services:
  db:
    image: postgres:11-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/${CHATONS_SERVICE:-limesurvey}/sql:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.fpm
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - data:/var/www/html
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/${CHATONS_SERVICE:-limesurvey}/upload:/var/www/html/upload

  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - app
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: ${CHATONS_SERVICE:-limesurvey}.${CHATONS_DOMAIN:-localhost}, www.${CHATONS_SERVICE:-limesurvey}.${CHATONS_DOMAIN:-localhost}"
    networks:
      - web
      - default
    volumes:
      - data:/var/www/html:ro
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/${CHATONS_SERVICE:-limesurvey}/upload:/var/www/html/upload:ro
