version: '3'

networks:
  web:
    external: true

services:
  web:
    build: ./nginx
    restart: unless-stopped
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/static/${CHATONS_STATIC_SITE:-static}:/usr/share/nginx/html
    labels:
      traefik.enable: "true"
      traefik.http.routers.static.rule: "Host(`${CHATONS_STATIC_SITE:-static}.${CHATONS_DOMAIN:-localhost}`)"
    networks:
      - web
