version: "3"

networks:
  web:
    external: true

services:
  app:
    image: chocobozzz/peertube:production-stretch
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PEERTUBE_WEBSERVER_HOSTNAME=${CHATONS_SERVICE}.${CHATONS_DOMAIN:-localhost}
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: ${CHATONS_SERVICE}.${CHATONS_DOMAIN:-localhost}, www.${CHATONS_SERVICE}.${CHATONS_DOMAIN:-localhost}"
    networks:
      - web
      - default
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/peertube/data:/data
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/peertube/config:/config

  db:
    image: postgres:10-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/peertube/postgres:/var/lib/postgresql/data

  redis:
    image: redis:4-alpine
    restart: unless-stopped
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/peertube/redis:/data
