version: "3"

services:
  postgres:
    restart: unless-stopped
    env_file: .env
    image: postgres:10-alpine
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/funkwhale/db:/var/lib/postgresql/data

  redis:
    restart: unless-stopped
    env_file: .env
    image: redis:4-alpine
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/funkwhale/redis:/data

  celeryworker:
    restart: unless-stopped
    image: funkwhale/funkwhale:${FUNKWHALE_VERSION:-latest}
    env_file: .env
    # Celery workers handle background tasks (such file imports or federation
    # messaging). The more processes a worker gets, the more tasks
    # can be processed in parallel. However, more processes also means
    # a bigger memory footprint.
    # By default, a worker will span a number of process equal to your number
    # of CPUs. You can adjust this, by explicitly setting the --concurrency
    # flag:
    #   celery -A funkwhale_api.taskapp worker -l INFO --concurrency=4
    command: celery -A funkwhale_api.taskapp worker -l INFO
    links:
      - postgres
      - redis
    environment:
      - C_FORCE_ROOT=true
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/funkwhale/music:${MUSIC_DIRECTORY_PATH-/music}:ro
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/funkwhale/media}:${MEDIA_ROOT}

  celerybeat:
    restart: unless-stopped
    image: funkwhale/funkwhale:${FUNKWHALE_VERSION:-latest}
    env_file: .env
    command: celery -A funkwhale_api.taskapp beat -l INFO
    links:
      - postgres
      - redis

  api:
    restart: unless-stopped
    image: funkwhale/funkwhale:${FUNKWHALE_VERSION:-latest}
    env_file: .env
    volumes:
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/funkwhale/music:${MUSIC_DIRECTORY_PATH-/music}:ro
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/funkwhale/media:${MEDIA_ROOT}
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/funkwhale/static}:${STATIC_ROOT}
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/funkwhale/frontend:/frontend
    ports:
      - 5000
    links:
      - postgres
      - redis

  nginx:
    image: nginx
    env_file:
      - .env
    environment:
      # Override those variables in your .env file if needed
      - "NGINX_MAX_BODY_SIZE=${NGINX_MAX_BODY_SIZE-30M}"
    volumes:
      - ./nginx/funkwhale.template:/etc/nginx/conf.d/funkwhale.template:ro
      - ./nginx/funkwhale_proxy.conf:/etc/nginx/funkwhale_proxy.conf:ro
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/funkwhale/music:${MUSIC_DIRECTORY_PATH-/music}:ro
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/funkwhale/media:${MEDIA_ROOT}
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/funkwhale/static}:${STATIC_ROOT}
      - ${CHATONS_ROOT_DIR:-/srv/chatons}/funkwhale/frontend:/frontend
    ports:
      # override those variables in your .env file if needed
      - "${FUNKWHALE_API_IP}:${FUNKWHALE_API_PORT}:80"
    command: >
        sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\"
        < /etc/nginx/conf.d/funkwhale.template
        > /etc/nginx/conf.d/default.conf
        && cat /etc/nginx/conf.d/default.conf
        && nginx -g 'daemon off;'"
    links:
      - api
